{% set version = "6.1.0" %}

package:
  name: octave
  version: {{ version }}

source:
  url: https://ftp.gnu.org/gnu/octave/octave-{{ version }}.tar.gz
  sha256: 6ff34e401658622c44094ecb67e497672e4337ca2d36c0702d0403ecc60b0a57

build:
  number: 0
  skip: True  # [win]
  binary_has_prefix_files:  # [unix]
    - bin/octave-{{ version }}  # [linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - sed
    - perl
    - ghostscript
    - pkg-config  # [linux]
    - bison
    - sundials
    - gperf
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxfixes') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - {{ cdt('libxcb') }}  # [linux]
    - {{ cdt('expat') }}  # [linux]
    - {{ cdt('libxext') }}  # [linux]
    - {{ cdt('libxrender') }}  # [linux]
    - {{ cdt('libxt') }}  # [linux]
    - {{ cdt('libxft') }}  # [linux]
    - {{ cdt('libx11-devel') }}  # [linux]
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
  host:
    - libblas
    - libcblas
    - liblapack
    - liblapacke
    - libglu
    - pcre
    - ghostscript
    - sundials
    - readline
    - arpack
    - curl
    - fftw
    - fontconfig
    - freetype
    - glpk
    - gnuplot
    - "hdf5>=1.10"
    - suitesparse
    - zlib
    - bzip2
    - portaudio
    - libsndfile
    - qscintilla2
    - qhull
    - graphicsmagick  # [linux]
    # Following gets linked at the end.
    - icu
    - ncurses
    - xz
    - libxml2
    - libpng
    - glib
    - qt
    - openssl
    - texinfo
    - gl2ps
    - fltk
  run:
    - ghostscript
    - texinfo
    - gl2ps
    - libblas * *mkl
    - mkl
    - libglu
    - fltk
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - pcre
    - readline
    - arpack
    - curl
    - sundials
    - {{ pin_compatible("fftw", max_pin="x.x") }}
    - fontconfig
    - freetype
    - glpk
    - gnuplot
    - "hdf5>=1.10"
    - {{ pin_compatible("suitesparse", max_pin="x.x") }}
    - zlib
    - bzip2
    - {{ pin_compatible("portaudio") }}
    - libsndfile
    - {{ pin_compatible("qscintilla2", max_pin="x.x") }}
    - qhull
    - {{ pin_compatible("graphicsmagick") }}   # [linux]
    # Following gets linked at the end.
    - icu
    - ncurses
    - xz
    - libxml2
    - libpng
    - glib
    - qt
    - openssl

test:
  requires:
    - coreutils
  commands:
    - octave --version
    - touch test_file.txt
    - octave test_file.txt

about:
  home: https://www.gnu.org/software/octave/
  license: GPL-3.0-or-later
  license_file: COPYING
  doc_url: https://www.gnu.org/software/octave/doc/interpreter/
  summary: 'GNU Octave is a high-level language, primarily intended for numerical computations'

extra:
  recipe-maintainers:
    - isuruf
    - ocefpaf
