travis:
  secure:
    BINSTAR_TOKEN: JDNiEB4NKjQl7JgcWj+mjIN1RXv5NlK3XE4eqUoFq17jyuHG6OXgH3dlKO92JNtki/fWsRrcluD3GHIykKswTukSjz8R1sBWP9fo4xODCdoDU2NZ04rrmbikfdH6RQJ89ueqrn3Dw81CDkiBmnTBX+Px5sTbhdmmvOU2UqYBC95AISt6WAJUEjzouEaY9kDbCPvq+CyS8IW6LyfCK2ia8ETw+uCqVntvRhE9TM/epyRG2+frphlZqhgBugugyvANDv2uESd3mHXoCnaraXxYrZRcI2CClz7zyVS6JM/C42UrdrvzD8t+sx9DG+fFNutdEmk+wHIGnVBJDbGEc+/C42t6PJ8uZFTaJZQKLqY1IsP77AgE+IdKB7l8K5O2WTgKiaMxX+qgtnALfoiBmE/L9S8ZjSvq00UXeeNm1CJ9Vg4D52pM0Dq+On4FekhFSoqFfH4+nObS6YxTjGemkaz8EvJLGrRsZadl8E+iYiAFXhNefpCq23KJfIPpAdCjcrWcvqULZaTLAx7WWvaj9FBoGM78AbTOVMo3olTGgsjG4zZnQAR/w2TPn7dU18fzhYTO5XJEJsAe9He4TBR4QUySwPS+TDowedgaQoYqwCFcmTXAQtKfdNm4iY5tbRJNjhLrnGHncWMN1wwwju7e+cBsu1vhg8W0gkyX6LwfpxZa7AU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
