travis:
  secure:
    BINSTAR_TOKEN: KjeznlpLK1pZsDkrR72grSfDcOMMqV1hRgfchypyQtAcvmOH/fc/lJr3F6PzSWftb1wTpdqznou9Kmgs5PZbcgbO/8KO7zvJp2MKaP1UNaqyxQxr5UvyqMu1drLf7rDscmTxXQy5QQk9iLPe1D6i4UKd4LSfSvRqZ7xo6T+rYX4GT3Ip3VTtSm6m+8oQUsO3iDkKXPSqMy9ZQwX9lArUQzRdiqulGKnTBX5AdftpVobx/wmjRc05J1VxsBmP209W9HajUr0XhTKUKpn0CXMLfVG+UYFc9CW3sRQcSBogz2Q5/BAEtqwiccPgERKR98YnRKb/tZxnJO4/ot6VfIJ9s3i7UE0m4oPKyKKhVhXwHt0M4Q85OGK3B1hNCvY2t1YBvlTpAcBeGawAHP5stkRBB5/pnVqRi6o6x2HbIB7EjuotWaAtVoMn1Ic5ZBKakeukEUDbnfC0PU71PJwzvtVU+0mxVfy//v3SeLAs9ZSWTI89fn1G61dwOEdJ9f89MrmM82Ewa0qLXYtZCfEJJctPSVsRAHztRaJw8DC5XTxeRXafIrdjN/Gf0MQlinDAQhIvQveXInOpgiIfJg51yM8TZsx0lrObX72s5ol0F1AckxfU9qvlZEYh/SaC3GHveLC6KeeE4VYw/tYdrDoN1Wryo2mBlW0YAMGbqIQUn+Rd8gE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
